package lk.RoyalGatesHotels.util;

public enum Routes {
    LOGINPAGE, WELCOMEPAGE, RECEPTIONDASHBOARD, ADMINDASHBOARD, ADMINEMPLOYEE, ADMINROOM, ADMINMEALPLAN, ADMINHALLS, ADMINUSER, ADMINMEALPACKAGEREPORT, ADMINHALLREPORT, EMPLOYEEREPORT, ADMINROOMREPORT,
    FORGOTPASSWORD, CONTACT, ABOUTUS, RECEPTIONRESERVATION, RECEPTIONMEALODERS, RECEPTIONMARKMAINTANCE, RECEPTIONCOMPLAIN, RECEPTIONGUEST, RECEPTIONPAYMENT, RECERVATIONDETAILS
}
